POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
  "title": "Task 3",
  "description": "Description of the new task",
  "isCompleted": false
}

###
GET http://localhost:3000/tasks HTTP/1.1

###
POST http://localhost:3000/task-relations/2/relate/1 HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/task-relations/1/related HTTP/1.1


