POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
  "title": "Task 3",
  "description": "Description of the new task",
  "isCompleted": false
}


###
GET http://localhost:3000/tasks HTTP/1.1

###
POST http://localhost:3000/tasks/1/relate/3 HTTP/1.1
content-type: application/json
